apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: ticketing
build:
  local:
    push: false
  artifacts:
    - image: matthxwpavin/ticketing/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: '**/*.go'
    - image: matthxwpavin/ticketing/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.jsx'
            dest: .
    - image: matthxwpavin/ticketing/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: '**/*.go'
    - image: matthxwpavin/ticketing/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: '**/*.go'
    - image: matthxwpavin/ticketing/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: '**/*.go'
    - image: matthxwpavin/ticketing/payment
      context: payment
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: .
            src: '**/*.go'
manifests:
  rawYaml:
    - infra/k8s/*
