# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: payment-test

on:
  push:
    branches: [ "main" ]
    paths: [ "payment/**" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "payment/**" ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.4'
      
    - name: Build
      run: cd payment && go build -v ./...

    - name: Test
      run: cd payment && go test -v ./...
